services:
  web:
    build: .
    environment:
      - DATABASE_PATH=/app/data/users.db
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - PYSPARK_PYTHON=/usr/local/bin/python
      - PYSPARK_DRIVER_PYTHON=/usr/local/bin/python
      - PYSPARK_SUBMIT_ARGS="--conf spark.driver.memory=4g --conf spark.executor.memory=2g pyspark-shell"
      - RABBITMQ_HOST=rabbitmq
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - .:/app
      - sqlite_data:/app/data
    ports:
      - "8501:8501"
    depends_on:
      - rabbitmq

  demo:
    build: .
    environment:
      - DATABASE_PATH=/app/data/users.db
      - POSTGRES_PORT=5432
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - PYSPARK_PYTHON=/usr/local/bin/python
      - PYSPARK_DRIVER_PYTHON=/usr/local/bin/python
      - PYSPARK_SUBMIT_ARGS="--conf spark.driver.memory=4g --conf spark.executor.memory=2g pyspark-shell"
      - RABBITMQ_HOST=rabbitmq
    command: streamlit run demo.py --server.port=8502 --server.address=0.0.0.0
    volumes:
      - .:/app
      - sqlite_data:/app/data
    ports:
      - "8502:8502"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"  # RabbitMQ management plugin (web interface)
      - "5672:5672"    # RabbitMQ AMQP port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  sqlite_data:
  rabbitmq_data:
